serverFiles:
  prometheus.yml:
    scrape_configs:
    - job_name: 'otel-k8s'
      static_configs:
      - targets: ['otelcontribcol.yaro-task.svc.cluster.local:5000']
    # - job_name: 'kubernetes-daemonsets'
    #   kubernetes_sd_configs:
    #     - role: pod
    #       namespaces:
    #         names:
    #           - yaro-task
    #   relabel_configs:
    #     - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
    #       action: keep
    #       regex: true
    #     - source_labels: [__meta_kubernetes_pod_name]
    #       action: keep
    #       regex: "otelcontribcol-.*"
    #     - source_labels: [__meta_kubernetes_pod_node_name]
    #       action: replace
    #       target_label: instance
    #     - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
    #       action: replace
    #       target_label: __address__
    #       regex: (.+);(.+)
    #       replacement: $1:$2