name: Apps Deployment

on:
  workflow_dispatch:

jobs:
  Deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up helm repositories 
      run: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo add grafana https://grafana.github.io/helm-charts
        helm repo add jfrog https://charts.jfrog.io
        helm repo update
    
    - name: Configure kubectl
      run: |
        mkdir $HOME/.kube/
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

    - name: Deploy Prometheus
      run: |
        helm upgrade --install --namespace yaro-task --create-namespace -f ./helm-values/prometheus-values.yaml prometheus-yaro prometheus-community/prometheus 

    - name: Deploy Grafana and Loki
      run: |
        helm upgrade --install --namespace yaro-task --create-namespace grafana-yaro grafana/grafana
        helm upgrade --install --namespace yaro-task --create-namespace -f ./helm-values/loki-values.yaml loki-yaro grafana/loki 

    - name: Deploy Jfrog
      run: |
        helm upgrade --install --namespace yaro-task --create-namespace -f ./helm-values/jfrog-values.yaml artifactory-yaro jfrog/artifactory-oss